// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      /Users/ericpeterford/Documents/UnityProjects/MedievalMath/Castle Math/Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string Logins_Entry1 = "Entry1";
        public static string Logins_Entry2 = "Entry2";
    }
}
