// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      /Projects/gde_unity_4.5/Assets/GameDataEditor/SampleScenes/GDESetDataScene/Resources/set_data_scene.json
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDESetTwoDListData : IGDEData
    {
        static string bool_2dlistKey = "bool_2dlist";
		public List<List<bool>>      bool_2dlist;
		public void Set_bool_2dlist()
		{
			GDEDataManager.SetBoolTwoDList(_key, bool_2dlistKey, bool_2dlist);
		}
		
        static string int_2dlistKey = "int_2dlist";
		public List<List<int>>      int_2dlist;
		public void Set_int_2dlist()
		{
			GDEDataManager.SetIntTwoDList(_key, int_2dlistKey, int_2dlist);
		}
		
        static string float_2dlistKey = "float_2dlist";
		public List<List<float>>      float_2dlist;
		public void Set_float_2dlist()
		{
			GDEDataManager.SetFloatTwoDList(_key, float_2dlistKey, float_2dlist);
		}
		
        static string string_2dlistKey = "string_2dlist";
		public List<List<string>>      string_2dlist;
		public void Set_string_2dlist()
		{
			GDEDataManager.SetStringTwoDList(_key, string_2dlistKey, string_2dlist);
		}
		
        static string vector2_2dlistKey = "vector2_2dlist";
		public List<List<Vector2>>      vector2_2dlist;
		public void Set_vector2_2dlist()
		{
			GDEDataManager.SetVector2TwoDList(_key, vector2_2dlistKey, vector2_2dlist);
		}
		
        static string vector3_2dlistKey = "vector3_2dlist";
		public List<List<Vector3>>      vector3_2dlist;
		public void Set_vector3_2dlist()
		{
			GDEDataManager.SetVector3TwoDList(_key, vector3_2dlistKey, vector3_2dlist);
		}
		
        static string vector4_2dlistKey = "vector4_2dlist";
		public List<List<Vector4>>      vector4_2dlist;
		public void Set_vector4_2dlist()
		{
			GDEDataManager.SetVector4TwoDList(_key, vector4_2dlistKey, vector4_2dlist);
		}
		
        static string color_2dlistKey = "color_2dlist";
		public List<List<Color>>      color_2dlist;
		public void Set_color_2dlist()
		{
			GDEDataManager.SetColorTwoDList(_key, color_2dlistKey, color_2dlist);
		}
		

        static string custom_2dlistKey = "custom_2dlist";
		public List<List<GDESetCustomData>>      custom_2dlist;
		public void Set_custom_2dlist()
		{
			GDEDataManager.SetCustomTwoDList(_key, custom_2dlistKey, custom_2dlist);
		}
		

        public GDESetTwoDListData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "SetTwoDList");
			
            dict.Merge(true, bool_2dlist.ToGDEDict(bool_2dlistKey));
            dict.Merge(true, int_2dlist.ToGDEDict(int_2dlistKey));
            dict.Merge(true, float_2dlist.ToGDEDict(float_2dlistKey));
            dict.Merge(true, string_2dlist.ToGDEDict(string_2dlistKey));
            dict.Merge(true, vector2_2dlist.ToGDEDict(vector2_2dlistKey));
            dict.Merge(true, vector3_2dlist.ToGDEDict(vector3_2dlistKey));
            dict.Merge(true, vector4_2dlist.ToGDEDict(vector4_2dlistKey));
            dict.Merge(true, color_2dlist.ToGDEDict(color_2dlistKey));

            dict.Merge(true, custom_2dlist.ToGDEDict(custom_2dlistKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
            if (custom_2dlist != null)
            {
                for(int x=0;  x<custom_2dlist.Count;  x++)
                {
                    if (custom_2dlist[x] != null)
                    {
                        for(int y=0;  y<custom_2dlist[x].Count;  y++)
                        {  
                            GDEDataManager.UpdateItem(custom_2dlist[x][y], rebuildKeyList);
                            custom_2dlist[x][y].UpdateCustomItems(rebuildKeyList);
                        }
                    }
                }
            }
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetBoolTwoDList(bool_2dlistKey, out bool_2dlist);
                dict.TryGetIntTwoDList(int_2dlistKey, out int_2dlist);
                dict.TryGetFloatTwoDList(float_2dlistKey, out float_2dlist);
                dict.TryGetStringTwoDList(string_2dlistKey, out string_2dlist);
                dict.TryGetVector2TwoDList(vector2_2dlistKey, out vector2_2dlist);
                dict.TryGetVector3TwoDList(vector3_2dlistKey, out vector3_2dlist);
                dict.TryGetVector4TwoDList(vector4_2dlistKey, out vector4_2dlist);
                dict.TryGetColorTwoDList(color_2dlistKey, out color_2dlist);

                dict.TryGetCustomTwoDList(custom_2dlistKey, out custom_2dlist);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            bool_2dlist = GDEDataManager.GetBoolTwoDList(_key, bool_2dlistKey, bool_2dlist);
            int_2dlist = GDEDataManager.GetIntTwoDList(_key, int_2dlistKey, int_2dlist);
            float_2dlist = GDEDataManager.GetFloatTwoDList(_key, float_2dlistKey, float_2dlist);
            string_2dlist = GDEDataManager.GetStringTwoDList(_key, string_2dlistKey, string_2dlist);
            vector2_2dlist = GDEDataManager.GetVector2TwoDList(_key, vector2_2dlistKey, vector2_2dlist);
            vector3_2dlist = GDEDataManager.GetVector3TwoDList(_key, vector3_2dlistKey, vector3_2dlist);
            vector4_2dlist = GDEDataManager.GetVector4TwoDList(_key, vector4_2dlistKey, vector4_2dlist);
            color_2dlist = GDEDataManager.GetColorTwoDList(_key, color_2dlistKey, color_2dlist);

            custom_2dlist = GDEDataManager.GetCustomTwoDList(_key, custom_2dlistKey, custom_2dlist);
        }

        public GDESetTwoDListData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDESetTwoDListData newClone = new GDESetTwoDListData(newKey);

            newClone.bool_2dlist = new List<List<bool>>(bool_2dlist);
			newClone.Set_bool_2dlist();
            newClone.int_2dlist = new List<List<int>>(int_2dlist);
			newClone.Set_int_2dlist();
            newClone.float_2dlist = new List<List<float>>(float_2dlist);
			newClone.Set_float_2dlist();
            newClone.string_2dlist = new List<List<string>>(string_2dlist);
			newClone.Set_string_2dlist();
            newClone.vector2_2dlist = new List<List<Vector2>>(vector2_2dlist);
			newClone.Set_vector2_2dlist();
            newClone.vector3_2dlist = new List<List<Vector3>>(vector3_2dlist);
			newClone.Set_vector3_2dlist();
            newClone.vector4_2dlist = new List<List<Vector4>>(vector4_2dlist);
			newClone.Set_vector4_2dlist();
            newClone.color_2dlist = new List<List<Color>>(color_2dlist);
			newClone.Set_color_2dlist();

            newClone.custom_2dlist = new List<List<GDESetCustomData>>(custom_2dlist);
			newClone.Set_custom_2dlist();

            return newClone;
		}

        public GDESetTwoDListData DeepClone()
		{
			GDESetTwoDListData newClone = ShallowClone();
            newClone.custom_2dlist = new List<List<GDESetCustomData>>();
			if (custom_2dlist != null)
			{
				foreach(var sublist in custom_2dlist)
				{
					var newSubList = new List<GDESetCustomData>();
					if (sublist != null)
					{
						foreach(var val in sublist)
							newSubList.Add(val.DeepClone());
					}
					newClone.custom_2dlist.Add(newSubList);
				}
			}
			newClone.Set_custom_2dlist();
            return newClone;
		}

        public void Reset_bool_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, bool_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetBoolTwoDList(bool_2dlistKey, out bool_2dlist);
        }
		
        public void Reset_int_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, int_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetIntTwoDList(int_2dlistKey, out int_2dlist);
        }
		
        public void Reset_float_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, float_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetFloatTwoDList(float_2dlistKey, out float_2dlist);
        }
		
        public void Reset_string_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, string_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetStringTwoDList(string_2dlistKey, out string_2dlist);
        }
		
        public void Reset_vector2_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, vector2_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetVector2TwoDList(vector2_2dlistKey, out vector2_2dlist);
        }
		
        public void Reset_vector3_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, vector3_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetVector3TwoDList(vector3_2dlistKey, out vector3_2dlist);
        }
		
        public void Reset_vector4_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, vector4_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetVector4TwoDList(vector4_2dlistKey, out vector4_2dlist);
        }
		
        public void Reset_color_2dlist()
        {
	        GDEDataManager.ResetToDefault(_key, color_2dlistKey);

	        Dictionary<string, object> dict;
	        GDEDataManager.Get(_key, out dict);
	        dict.TryGetColorTwoDList(color_2dlistKey, out color_2dlist);
        }
		

        public void Reset_custom_2dlist()
		{
			GDEDataManager.ResetToDefault(_key, custom_2dlistKey);

			Dictionary<string, object> dict;
			GDEDataManager.Get(_key, out dict);

			dict.TryGetCustomTwoDList(custom_2dlistKey, out custom_2dlist);
			custom_2dlist = GDEDataManager.GetCustomTwoDList(_key, custom_2dlistKey, custom_2dlist);

			custom_2dlist.ForEach(x => x.ForEach(y => y.ResetAll()));
		}

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, custom_2dlistKey);
            GDEDataManager.ResetToDefault(_key, color_2dlistKey);
            GDEDataManager.ResetToDefault(_key, vector4_2dlistKey);
            GDEDataManager.ResetToDefault(_key, vector3_2dlistKey);
            GDEDataManager.ResetToDefault(_key, vector2_2dlistKey);
            GDEDataManager.ResetToDefault(_key, string_2dlistKey);
            GDEDataManager.ResetToDefault(_key, float_2dlistKey);
            GDEDataManager.ResetToDefault(_key, int_2dlistKey);
            GDEDataManager.ResetToDefault(_key, bool_2dlistKey);

            Reset_custom_2dlist();

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
