// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      /Projects/gde_unity_4.5/Assets/GameDataEditor/SampleScenes/GDESetDataScene/Resources/set_data_scene.json
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections.Generic;

using GameDataEditor;

namespace GameDataEditor
{
    public class GDESetCustomData : IGDEData
    {
        static string bool_fieldKey = "bool_field";
		bool _bool_field;
        public bool bool_field
        {
            get { return _bool_field; }
            set {
                if (_bool_field != value)
                {
                    _bool_field = value;
					GDEDataManager.SetBool(_key, bool_fieldKey, _bool_field);
                }
            }
        }

        static string int_fieldKey = "int_field";
		int _int_field;
        public int int_field
        {
            get { return _int_field; }
            set {
                if (_int_field != value)
                {
                    _int_field = value;
					GDEDataManager.SetInt(_key, int_fieldKey, _int_field);
                }
            }
        }

        static string float_fieldKey = "float_field";
		float _float_field;
        public float float_field
        {
            get { return _float_field; }
            set {
                if (_float_field != value)
                {
                    _float_field = value;
					GDEDataManager.SetFloat(_key, float_fieldKey, _float_field);
                }
            }
        }

        static string descriptionKey = "description";
		string _description;
        public string description
        {
            get { return _description; }
            set {
                if (_description != value)
                {
                    _description = value;
					GDEDataManager.SetString(_key, descriptionKey, _description);
                }
            }
        }

        static string string_fieldKey = "string_field";
		string _string_field;
        public string string_field
        {
            get { return _string_field; }
            set {
                if (_string_field != value)
                {
                    _string_field = value;
					GDEDataManager.SetString(_key, string_fieldKey, _string_field);
                }
            }
        }

        static string vector2_fieldKey = "vector2_field";
		Vector2 _vector2_field;
        public Vector2 vector2_field
        {
            get { return _vector2_field; }
            set {
                if (_vector2_field != value)
                {
                    _vector2_field = value;
					GDEDataManager.SetVector2(_key, vector2_fieldKey, _vector2_field);
                }
            }
        }

        static string vector3_fieldKey = "vector3_field";
		Vector3 _vector3_field;
        public Vector3 vector3_field
        {
            get { return _vector3_field; }
            set {
                if (_vector3_field != value)
                {
                    _vector3_field = value;
					GDEDataManager.SetVector3(_key, vector3_fieldKey, _vector3_field);
                }
            }
        }

        static string color_fieldKey = "color_field";
		Color _color_field;
        public Color color_field
        {
            get { return _color_field; }
            set {
                if (_color_field != value)
                {
                    _color_field = value;
					GDEDataManager.SetColor(_key, color_fieldKey, _color_field);
                }
            }
        }

        public GDESetCustomData(string key) : base(key)
        {
            GDEDataManager.RegisterItem(this.SchemaName(), key);
        }
        public override Dictionary<string, object> SaveToDict()
		{
			var dict = new Dictionary<string, object>();
			dict.Add(GDMConstants.SchemaKey, "SetCustom");
			
            dict.Merge(true, bool_field.ToGDEDict(bool_fieldKey));
            dict.Merge(true, int_field.ToGDEDict(int_fieldKey));
            dict.Merge(true, float_field.ToGDEDict(float_fieldKey));
            dict.Merge(true, description.ToGDEDict(descriptionKey));
            dict.Merge(true, string_field.ToGDEDict(string_fieldKey));
            dict.Merge(true, vector2_field.ToGDEDict(vector2_fieldKey));
            dict.Merge(true, vector3_field.ToGDEDict(vector3_fieldKey));
            dict.Merge(true, color_field.ToGDEDict(color_fieldKey));
            return dict;
		}

        public override void UpdateCustomItems(bool rebuildKeyList)
        {
        }

        public override void LoadFromDict(string dataKey, Dictionary<string, object> dict)
        {
            _key = dataKey;

			if (dict == null)
				LoadFromSavedData(dataKey);
			else
			{
                dict.TryGetBool(bool_fieldKey, out _bool_field);
                dict.TryGetInt(int_fieldKey, out _int_field);
                dict.TryGetFloat(float_fieldKey, out _float_field);
                dict.TryGetString(descriptionKey, out _description);
                dict.TryGetString(string_fieldKey, out _string_field);
                dict.TryGetVector2(vector2_fieldKey, out _vector2_field);
                dict.TryGetVector3(vector3_fieldKey, out _vector3_field);
                dict.TryGetColor(color_fieldKey, out _color_field);
                LoadFromSavedData(dataKey);
			}
		}

        public override void LoadFromSavedData(string dataKey)
		{
			_key = dataKey;
			
            _bool_field = GDEDataManager.GetBool(_key, bool_fieldKey, _bool_field);
            _int_field = GDEDataManager.GetInt(_key, int_fieldKey, _int_field);
            _float_field = GDEDataManager.GetFloat(_key, float_fieldKey, _float_field);
            _description = GDEDataManager.GetString(_key, descriptionKey, _description);
            _string_field = GDEDataManager.GetString(_key, string_fieldKey, _string_field);
            _vector2_field = GDEDataManager.GetVector2(_key, vector2_fieldKey, _vector2_field);
            _vector3_field = GDEDataManager.GetVector3(_key, vector3_fieldKey, _vector3_field);
            _color_field = GDEDataManager.GetColor(_key, color_fieldKey, _color_field);
        }

        public GDESetCustomData ShallowClone()
		{
			string newKey = Guid.NewGuid().ToString();
			GDESetCustomData newClone = new GDESetCustomData(newKey);

            newClone.bool_field = bool_field;
            newClone.int_field = int_field;
            newClone.float_field = float_field;
            newClone.description = description;
            newClone.string_field = string_field;
            newClone.vector2_field = vector2_field;
            newClone.vector3_field = vector3_field;
            newClone.color_field = color_field;

            return newClone;
		}

        public GDESetCustomData DeepClone()
		{
			GDESetCustomData newClone = ShallowClone();
            return newClone;
		}

        public void Reset_bool_field()
        {
            GDEDataManager.ResetToDefault(_key, bool_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetBool(bool_fieldKey, out _bool_field);
        }

        public void Reset_int_field()
        {
            GDEDataManager.ResetToDefault(_key, int_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetInt(int_fieldKey, out _int_field);
        }

        public void Reset_float_field()
        {
            GDEDataManager.ResetToDefault(_key, float_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetFloat(float_fieldKey, out _float_field);
        }

        public void Reset_description()
        {
            GDEDataManager.ResetToDefault(_key, descriptionKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(descriptionKey, out _description);
        }

        public void Reset_string_field()
        {
            GDEDataManager.ResetToDefault(_key, string_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetString(string_fieldKey, out _string_field);
        }

        public void Reset_vector2_field()
        {
            GDEDataManager.ResetToDefault(_key, vector2_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetVector2(vector2_fieldKey, out _vector2_field);
        }

        public void Reset_vector3_field()
        {
            GDEDataManager.ResetToDefault(_key, vector3_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetVector3(vector3_fieldKey, out _vector3_field);
        }

        public void Reset_color_field()
        {
            GDEDataManager.ResetToDefault(_key, color_fieldKey);

            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            dict.TryGetColor(color_fieldKey, out _color_field);
        }

        public void ResetAll()
        {
            GDEDataManager.ResetToDefault(_key, descriptionKey);
            GDEDataManager.ResetToDefault(_key, int_fieldKey);
            GDEDataManager.ResetToDefault(_key, float_fieldKey);
            GDEDataManager.ResetToDefault(_key, vector2_fieldKey);
            GDEDataManager.ResetToDefault(_key, vector3_fieldKey);
            GDEDataManager.ResetToDefault(_key, color_fieldKey);
            GDEDataManager.ResetToDefault(_key, string_fieldKey);
            GDEDataManager.ResetToDefault(_key, bool_fieldKey);


            Dictionary<string, object> dict;
            GDEDataManager.Get(_key, out dict);
            LoadFromDict(_key, dict);
        }
    }
}
